### ISSUE TITLE
Feature request: Skip pages

### ISSUE THREAD

**Issue by Wyrrrd** [J-CPelletier/webcomix#72]
I follow some webcomics that just throw other webcomics in the main rotation. It would be nice to have pages be or be not downloaded depending on an allowlist/blocklist condition (also pausing the page index incrementation).

**Comment by J-CPelletier** [comment]
Are you aware if the URLs associated with the images of these other webcomics have some form of pattern? If so, I could add a feature to filter them out with a blocklist condition.

**Comment by Wyrrrd** [comment]
For my case there is a pattern in the URL, but I guess it would be more versatile to have an XPath to blocklist. This way, one could for example check for page title if needed.

**Comment by J-CPelletier** [comment]
This sounds like a good idea, I'll try to implement something like this by adding both URLs and XPath options. This should work well in cases where a single comic page is present within each webpages, but won't necessarily be usable if we have multiple comic pages within the same webpage. This edge case will most likely be pretty rare, since this feature was mostly done because it's supported on some websites and that it cuts down the download times quite a bit.

**Comment by J-CPelletier** [comment]
I just added the `--block-xpath` option, I'll be releasing a new version shortly
